import * as THREE from '../vendor/three.module.js';
import {makeIntent,applyBridgeResponse} from './protocol.js';
import {assertEffectRecipe,applyEffectRecipe} from './effect-recipe.js';

let appState={projection:null,effects:[]},creature=null,resourceMesh=null,relayVisual=null,couplerVisual=null,rebuildCount=0,candidateEffectRecipe=null,spawnedEntityIds=[],relayAsset=null;
const canvas=document.querySelector('#world'),renderer=new THREE.WebGLRenderer({canvas,antialias:true}),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(52,1,.1,100);
renderer.setPixelRatio(Math.min(devicePixelRatio,2));scene.background=new THREE.Color(0x05070b);scene.fog=new THREE.FogExp2(0x07101a,.035);camera.position.set(0,4.4,9.5);
scene.add(new THREE.HemisphereLight(0x84dfff,0x07090d,2.1));const key=new THREE.DirectionalLight(0xb5f2ff,2.4);key.position.set(4,8,6);scene.add(key);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(36,36,40,40),new THREE.MeshStandardMaterial({color:0x0c1b22,roughness:.95,metalness:.05}));floor.rotation.x=-Math.PI/2;floor.position.y=-1.5;scene.add(floor);

function isRelay(p=appState.projection){return p?.contract==='relay-runtime-projection.v0.1'}
function disposeObject(o){if(!o)return;o.traverse?.(c=>{c.geometry?.dispose?.();if(c.material)(Array.isArray(c.material)?c.material:[c.material]).forEach(m=>m.dispose?.())});scene.remove(o)}
function rebuildCreature(p){disposeObject(creature);creature=new THREE.Group();rebuildCount+=1;const scale=p.actor.lineage.stage==='adult'?1.25:.9;const body=new THREE.Mesh(new THREE.IcosahedronGeometry(1.25*scale,2),new THREE.MeshStandardMaterial({color:0x4fc3d6,roughness:.35,metalness:.25,emissive:0x082d36,emissiveIntensity:.7}));body.scale.set(1.25,.75,1);creature.add(body);const mat=new THREE.MeshStandardMaterial({color:0xa8f4ff,roughness:.18,metalness:.55,emissive:0x1d6f82,emissiveIntensity:.85});const count=6+p.actor.lineage.organs.length*4;for(let i=0;i<count;i++){const shard=new THREE.Mesh(new THREE.ConeGeometry(.12,.65,5),mat),a=(i/count)*Math.PI*2;shard.position.set(Math.cos(a)*1.1*scale,.2+Math.sin(i*1.7)*.35,Math.sin(a)*.9*scale);shard.rotation.z=-a+.3;shard.rotation.x=.35;creature.add(shard)}creature.position.y=.1;scene.add(creature);document.body.dataset.rebuildCount=String(rebuildCount)}
function rebuildResource(p){disposeObject(resourceMesh);const r=p.visible_resources?.[0];if(!r){resourceMesh=null;return}resourceMesh=new THREE.Mesh(new THREE.DodecahedronGeometry(.55,0),new THREE.MeshStandardMaterial({color:0xe6ff8a,emissive:0x5a6b13,emissiveIntensity:.8}));resourceMesh.position.set(2.6,-.65,.6);scene.add(resourceMesh)}
function rebuildRelay(p){disposeObject(relayVisual);relayVisual=new THREE.Group();rebuildCount+=1;const active=p.relay.active, repaired=p.relay.condition==='repaired';const bodyMat=new THREE.MeshStandardMaterial({color:active?0x6fe6ff:repaired?0x7899aa:0x52616a,roughness:.32,metalness:.72,emissive:active?0x176b7a:0x071117,emissiveIntensity:active?1.1:.25});const spine=new THREE.Mesh(new THREE.CylinderGeometry(.4,.55,3.4,16),bodyMat);relayVisual.add(spine);for(let i=0;i<3;i++){const ring=new THREE.Mesh(new THREE.TorusGeometry(.95+i*.18,.08,8,28),bodyMat);ring.rotation.x=Math.PI/2;ring.position.y=-.9+i*.9;relayVisual.add(ring)}const cap=new THREE.Mesh(new THREE.OctahedronGeometry(.55,0),new THREE.MeshStandardMaterial({color:0xb9f8ff,emissive:0x1d6f82,emissiveIntensity:active?1.4:.35,metalness:.4,roughness:.2}));cap.position.y=1.95;relayVisual.add(cap);relayVisual.position.set(1.4,.1,0);scene.add(relayVisual);document.body.dataset.rebuildCount=String(rebuildCount)}
function rebuildCoupler(p){disposeObject(couplerVisual);const visible=p.visible_items?.find(x=>x.entity_id==='item.phase-coupler');if(!visible){couplerVisual=null;return}couplerVisual=new THREE.Mesh(new THREE.DodecahedronGeometry(.5,0),new THREE.MeshStandardMaterial({color:0xffd76a,emissive:0x6b4a13,emissiveIntensity:.8,metalness:.5,roughness:.25}));couplerVisual.position.set(-2.1,-.65,.4);scene.add(couplerVisual)}
function renderProjection(p){if(isRelay(p)){disposeObject(creature);creature=null;disposeObject(resourceMesh);resourceMesh=null;rebuildRelay(p);rebuildCoupler(p)}else{disposeObject(relayVisual);relayVisual=null;disposeObject(couplerVisual);couplerVisual=null;rebuildCreature(p);rebuildResource(p)}}
function applyEffect(e){if(e==='rebuild-creature')rebuildCreature(appState.projection);if(e==='pulse-feed'&&creature){creature.scale.setScalar(1.12);setTimeout(()=>creature?.scale.setScalar(1),160)}if(e==='rift-transition'){scene.background=new THREE.Color(0x160b2c);setTimeout(()=>scene.background=new THREE.Color(0x05070b),250)}if(e==='relay-rebuild')rebuildRelay(appState.projection);if((e==='inspect-pulse'||e==='relay-activated')&&relayVisual){relayVisual.scale.setScalar(1.08);setTimeout(()=>relayVisual?.scale.setScalar(1),180)}}
function setStat(labelId,statId,label,value){document.querySelector(labelId).textContent=label;document.querySelector(statId).textContent=value??'—'}
function configureButtons(){const allowed=new Set(appState.projection?.available_actions??[]);document.querySelectorAll('[data-intent]').forEach(b=>b.hidden=!allowed.has(b.dataset.intent))}
function syncDOM(){const p=appState.projection;if(!p)return;document.body.dataset.worldEntityId=p.actor.world_entity_id;document.body.dataset.presentationInstanceId=p.presentation_instance_id;document.body.dataset.generation=String(p.generation);document.querySelector('#identity').textContent=`${p.actor.world_entity_id} · gen ${p.generation} · ${p.actor.room_id}`;if(isRelay(p)){document.querySelector('#world-title').textContent='Relay Station';Object.assign(document.body.dataset,{relayEntityId:p.relay.world_entity_id,relayCondition:p.relay.condition,relayActive:String(p.relay.active),contractStatus:p.actor.contract_status,cargoId:p.actor.cargo_id??''});setStat('#label-a','#stat-a','Relay',p.relay.condition);setStat('#label-b','#stat-b','Contract',p.actor.contract_status);setStat('#label-c','#stat-c','Cargo',p.actor.cargo_id??'empty');setStat('#label-d','#stat-d','Signal',p.relay.active?'online':'offline')}else{document.querySelector('#world-title').textContent='Alien Lineage';Object.assign(document.body.dataset,{stage:p.actor.lineage.stage,worldline:p.actor.worldline??'origin'});setStat('#label-a','#stat-a','Stage',p.actor.lineage.stage);setStat('#label-b','#stat-b','Energy',p.actor.biology.energy);setStat('#label-c','#stat-c','Growth',p.actor.biology.growth_points);setStat('#label-d','#stat-d','World',p.actor.worldline??'origin')}configureButtons()}
function log(t){const el=document.querySelector('#log');el.textContent=(t+'\n'+el.textContent).slice(0,2600)}
async function loadCandidateEffectRecipe(){const url=new URLSearchParams(location.search).get('effectRecipe');if(!url)return null;const response=await fetch(url,{cache:'no-store'});if(!response.ok)throw new Error(`effect recipe ${response.status}`);candidateEffectRecipe=assertEffectRecipe(await response.json());document.body.dataset.effectRecipeLoaded='true';return candidateEffectRecipe}
async function loadRelayAsset(){if(!isRelay())return null;const response=await fetch('./assets/relay-core.visual.json',{cache:'no-store'});if(!response.ok)throw new Error(`relay asset ${response.status}`);relayAsset=await response.json();if(relayAsset.asset!=='relay-core-procedural')throw new Error('relay asset identity mismatch');document.body.dataset.relayAssetLoaded='true';return relayAsset}
function applyCandidateRecipe(events){if(!candidateEffectRecipe)return;for(const event of events??[]){if(event.event_type!==candidateEffectRecipe.event_type)continue;const result=applyEffectRecipe(candidateEffectRecipe,{creature,relay:relayVisual});if(result.applied)document.body.dataset.effectRecipeApplied='true'}}
async function getProjection(){const r=await fetch('/api/projection',{cache:'no-store'});if(!r.ok)throw new Error(`projection ${r.status}`);return r.json()}
async function reloadScene(){const r=await fetch('/api/reload',{method:'POST'});if(!r.ok)throw new Error(`reload ${r.status}`);appState={projection:await r.json(),effects:[]};renderProjection(appState.projection);syncDOM();return appState.projection}
async function sendIntent(type,fields={}){const r=await fetch('/api/action',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(makeIntent(appState.projection,type,fields))}),response=await r.json();if(!r.ok)throw new Error(response.message??`action ${r.status}`);appState=applyBridgeResponse(appState,response);for(const id of response.receipt.changed_entities??[]){if(!spawnedEntityIds.includes(id))spawnedEntityIds.push(id)}if(spawnedEntityIds.length)document.body.dataset.spawnedEntityIds=spawnedEntityIds.join(',');syncDOM();if(isRelay())rebuildCoupler(appState.projection);else rebuildResource(appState.projection);appState.effects.forEach(applyEffect);applyCandidateRecipe(response.events);log(`${type}: ${response.receipt.status} — ${response.receipt.message}`);return response}
const actions={
  'move-north':()=>sendIntent('move',{direction:'north'}),'move-south':()=>sendIntent('move',{direction:'south'}),'move-east':()=>sendIntent('move',{direction:'east'}),
  feed:()=>sendIntent('feed',{target_id:'item.mineral-bloom'}),mutate:()=>sendIntent('mutate',{organ_id:'organ.crystal-gill'}),grow:()=>sendIntent('grow'),lay_egg:()=>sendIntent('lay_egg'),hatch:()=>sendIntent('hatch'),enter_rift:()=>sendIntent('enter_rift',{rift_id:'rift.echo'}),
  'inspect-coupler':()=>sendIntent('inspect',{target_id:'item.phase-coupler'}),'pick-up':()=>sendIntent('pick_up',{target_id:'item.phase-coupler'}),'inspect-relay':()=>sendIntent('inspect',{target_id:'facility.storm-relay-core.001'}),deliver:()=>sendIntent('deliver',{target_id:'facility.storm-relay-core.001'}),repair:()=>sendIntent('repair',{target_id:'facility.storm-relay-core.001'}),activate:()=>sendIntent('activate',{target_id:'facility.storm-relay-core.001'}),reload:()=>reloadScene()
};
document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>actions[b.dataset.action]?.().catch(e=>log(`ERROR: ${e.message}`))));
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();function frame(t){if(creature)creature.rotation.y=t*.00022;if(relayVisual)relayVisual.rotation.y=Math.sin(t*.0003)*.08;renderer.render(scene,camera);requestAnimationFrame(frame)}requestAnimationFrame(frame);
async function smoke(){const entity=appState.projection.actor.world_entity_id,gen=appState.projection.generation;await reloadScene();if(appState.projection.actor.world_entity_id!==entity||appState.projection.generation<=gen)throw new Error('reload identity invariant failed');if(isRelay()){await sendIntent('inspect',{target_id:'item.phase-coupler'});await sendIntent('pick_up',{target_id:'item.phase-coupler'});await sendIntent('move',{direction:'east'});await sendIntent('move',{direction:'east'});await sendIntent('inspect',{target_id:'facility.storm-relay-core.001'});await sendIntent('deliver',{target_id:'facility.storm-relay-core.001'});await sendIntent('repair',{target_id:'facility.storm-relay-core.001'});await sendIntent('activate',{target_id:'facility.storm-relay-core.001'});if(!appState.projection.relay.active||appState.projection.actor.contract_status!=='activated')throw new Error('relay runtime projection did not activate');if(!spawnedEntityIds.includes('signal.beacon.001'))throw new Error('relay beacon spawn evidence missing');if(candidateEffectRecipe&&document.body.dataset.effectRecipeApplied!=='true')throw new Error('relay candidate effect recipe was not applied')}else{await sendIntent('move',{direction:'north'});await sendIntent('feed',{target_id:'item.mineral-bloom'});await sendIntent('feed',{target_id:'item.mineral-bloom'});await sendIntent('feed',{target_id:'item.mineral-bloom'});await sendIntent('mutate',{organ_id:'organ.crystal-gill'});if(!appState.projection.actor.lineage.organs.includes('organ.crystal-gill')||rebuildCount<2)throw new Error('mutation presentation rebuild failed');if(candidateEffectRecipe&&document.body.dataset.effectRecipeApplied!=='true')throw new Error('candidate effect recipe was not applied');if(new URLSearchParams(location.search).get('spawn')==='1'){await sendIntent('grow');await sendIntent('move',{direction:'south'});await sendIntent('lay_egg');await sendIntent('hatch');if(!spawnedEntityIds.includes('egg.crystal-filterer.001')||!spawnedEntityIds.includes('creature.crystal-filterer.child.001'))throw new Error('transaction-safe spawn evidence missing')}}document.body.dataset.smokePassed='true'}
await loadCandidateEffectRecipe();appState={projection:await getProjection(),effects:[]};await loadRelayAsset();renderProjection(appState.projection);syncDOM();document.body.dataset.ready='true';window.__AWA_PRESENTATION_READY__=true;if(new URLSearchParams(location.search).get('smoke')==='1')smoke().catch(e=>{document.body.dataset.smokeError=e.message;log(`SMOKE ERROR: ${e.message}`)});
