import * as THREE from '../vendor/three.module.js';
import {makeIntent,applyBridgeResponse} from './protocol.js';
import {assertEffectRecipe,applyEffectRecipe} from './effect-recipe.js';
let appState={projection:null,effects:[]},creature=null,resourceMesh=null,rebuildCount=0,candidateEffectRecipe=null,spawnedEntityIds=[];
const canvas=document.querySelector('#world'),renderer=new THREE.WebGLRenderer({canvas,antialias:true}),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(52,1,.1,100); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); scene.background=new THREE.Color(0x05070b); scene.fog=new THREE.FogExp2(0x07101a,.035); camera.position.set(0,4.4,9.5); scene.add(new THREE.HemisphereLight(0x84dfff,0x07090d,2.1)); const key=new THREE.DirectionalLight(0xb5f2ff,2.4); key.position.set(4,8,6); scene.add(key); const floor=new THREE.Mesh(new THREE.PlaneGeometry(36,36,40,40),new THREE.MeshStandardMaterial({color:0x0c1b22,roughness:.95,metalness:.05})); floor.rotation.x=-Math.PI/2; floor.position.y=-1.5; scene.add(floor);
function disposeObject(o){if(!o)return;o.traverse?.(c=>{c.geometry?.dispose?.();if(c.material)(Array.isArray(c.material)?c.material:[c.material]).forEach(m=>m.dispose?.())});scene.remove(o)}
function rebuildCreature(p){disposeObject(creature);creature=new THREE.Group();rebuildCount+=1;const scale=p.actor.lineage.stage==='adult'?1.25:.9;const body=new THREE.Mesh(new THREE.IcosahedronGeometry(1.25*scale,2),new THREE.MeshStandardMaterial({color:0x4fc3d6,roughness:.35,metalness:.25,emissive:0x082d36,emissiveIntensity:.7}));body.scale.set(1.25,.75,1);creature.add(body);const mat=new THREE.MeshStandardMaterial({color:0xa8f4ff,roughness:.18,metalness:.55,emissive:0x1d6f82,emissiveIntensity:.85});const count=6+p.actor.lineage.organs.length*4;for(let i=0;i<count;i++){const shard=new THREE.Mesh(new THREE.ConeGeometry(.12,.65,5),mat),a=(i/count)*Math.PI*2;shard.position.set(Math.cos(a)*1.1*scale,.2+Math.sin(i*1.7)*.35,Math.sin(a)*.9*scale);shard.rotation.z=-a+.3;shard.rotation.x=.35;creature.add(shard)}creature.position.y=.1;scene.add(creature);document.body.dataset.rebuildCount=String(rebuildCount)}
function rebuildResource(p){disposeObject(resourceMesh);const r=p.visible_resources[0];if(!r){resourceMesh=null;return}resourceMesh=new THREE.Mesh(new THREE.DodecahedronGeometry(.55,0),new THREE.MeshStandardMaterial({color:0xe6ff8a,emissive:0x5a6b13,emissiveIntensity:.8}));resourceMesh.position.set(2.6,-.65,.6);scene.add(resourceMesh)}
function applyEffect(e){if(e==='rebuild-creature')rebuildCreature(appState.projection);if(e==='pulse-feed'&&creature){creature.scale.setScalar(1.12);setTimeout(()=>creature?.scale.setScalar(1),160)}if(e==='rift-transition'){scene.background=new THREE.Color(0x160b2c);setTimeout(()=>scene.background=new THREE.Color(0x05070b),250)}}
function syncDOM(){const p=appState.projection;if(!p)return;Object.assign(document.body.dataset,{worldEntityId:p.actor.world_entity_id,presentationInstanceId:p.presentation_instance_id,generation:String(p.generation),stage:p.actor.lineage.stage,worldline:p.actor.worldline??'origin'});document.querySelector('#identity').textContent=`${p.actor.world_entity_id} · gen ${p.generation} · ${p.actor.room_id}`;document.querySelector('#stage').textContent=p.actor.lineage.stage;document.querySelector('#energy').textContent=p.actor.biology.energy;document.querySelector('#growth').textContent=p.actor.biology.growth_points;document.querySelector('#worldline').textContent=p.actor.worldline??'origin'}
function log(t){const el=document.querySelector('#log');el.textContent=(t+'\n'+el.textContent).slice(0,2600)}
async function loadCandidateEffectRecipe(){const url=new URLSearchParams(location.search).get('effectRecipe');if(!url)return null;const response=await fetch(url,{cache:'no-store'});if(!response.ok)throw new Error(`effect recipe ${response.status}`);candidateEffectRecipe=assertEffectRecipe(await response.json());document.body.dataset.effectRecipeLoaded='true';return candidateEffectRecipe}
function applyCandidateRecipe(events){if(!candidateEffectRecipe)return;for(const event of events??[]){if(event.event_type!==candidateEffectRecipe.event_type)continue;const result=applyEffectRecipe(candidateEffectRecipe,{creature});if(result.applied)document.body.dataset.effectRecipeApplied='true'}}
async function getProjection(){const r=await fetch('/api/projection',{cache:'no-store'});if(!r.ok)throw new Error(`projection ${r.status}`);return r.json()}
async function reloadScene(){const r=await fetch('/api/reload',{method:'POST'});if(!r.ok)throw new Error(`reload ${r.status}`);appState={projection:await r.json(),effects:[]};rebuildCreature(appState.projection);rebuildResource(appState.projection);syncDOM();return appState.projection}
async function sendIntent(type,fields={}){const r=await fetch('/api/action',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(makeIntent(appState.projection,type,fields))}),response=await r.json();if(!r.ok)throw new Error(response.message??`action ${r.status}`);appState=applyBridgeResponse(appState,response);for(const id of response.receipt.changed_entities??[]){if(!spawnedEntityIds.includes(id))spawnedEntityIds.push(id)}if(spawnedEntityIds.length)document.body.dataset.spawnedEntityIds=spawnedEntityIds.join(',');syncDOM();rebuildResource(appState.projection);appState.effects.forEach(applyEffect);applyCandidateRecipe(response.events);log(`${type}: ${response.receipt.status} — ${response.receipt.message}`);return response}
const actions={'move-north':()=>sendIntent('move',{direction:'north'}),'move-south':()=>sendIntent('move',{direction:'south'}),'move-east':()=>sendIntent('move',{direction:'east'}),feed:()=>sendIntent('feed',{target_id:'item.mineral-bloom'}),mutate:()=>sendIntent('mutate',{organ_id:'organ.crystal-gill'}),grow:()=>sendIntent('grow'),lay_egg:()=>sendIntent('lay_egg'),hatch:()=>sendIntent('hatch'),enter_rift:()=>sendIntent('enter_rift',{rift_id:'rift.echo'}),reload:()=>reloadScene()};document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>actions[b.dataset.action]().catch(e=>log(`ERROR: ${e.message}`))));function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();function frame(t){if(creature)creature.rotation.y=t*.00022;renderer.render(scene,camera);requestAnimationFrame(frame)}requestAnimationFrame(frame);
async function smoke(){const entity=appState.projection.actor.world_entity_id,gen=appState.projection.generation;await reloadScene();if(appState.projection.actor.world_entity_id!==entity||appState.projection.generation<=gen)throw new Error('reload identity invariant failed');await sendIntent('move',{direction:'north'});await sendIntent('feed',{target_id:'item.mineral-bloom'});await sendIntent('feed',{target_id:'item.mineral-bloom'});await sendIntent('feed',{target_id:'item.mineral-bloom'});await sendIntent('mutate',{organ_id:'organ.crystal-gill'});if(!appState.projection.actor.lineage.organs.includes('organ.crystal-gill')||rebuildCount<2)throw new Error('mutation presentation rebuild failed');if(candidateEffectRecipe&&document.body.dataset.effectRecipeApplied!=='true')throw new Error('candidate effect recipe was not applied');if(new URLSearchParams(location.search).get('spawn')==='1'){await sendIntent('grow');await sendIntent('move',{direction:'south'});await sendIntent('lay_egg');await sendIntent('hatch');if(!spawnedEntityIds.includes('egg.crystal-filterer.001')||!spawnedEntityIds.includes('creature.crystal-filterer.child.001'))throw new Error('transaction-safe spawn evidence missing')}document.body.dataset.smokePassed='true'}
await loadCandidateEffectRecipe();appState={projection:await getProjection(),effects:[]};rebuildCreature(appState.projection);rebuildResource(appState.projection);syncDOM();document.body.dataset.ready='true';window.__AWA_PRESENTATION_READY__=true;if(new URLSearchParams(location.search).get('smoke')==='1')smoke().catch(e=>{document.body.dataset.smokeError=e.message;log(`SMOKE ERROR: ${e.message}`)});
